services:
  server:
    build:
      context: server
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:16.3-alpine3.20"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 60s
      retries: 10
      start_period: 3s
