name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Report coverage
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-manager: pnpm
